services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: pnads
      POSTGRES_USER: pnads
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pnads"]
      interval: 5s
      timeout: 3s
      retries: 10

  pnads:
    build: .
    container_name: pnads
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: pnads
      DB_USER: pnads
      DB_PASSWORD: secret
      LOG_LEVEL: info
      OUI_FILE: /app/data/oui.csv
      API_PORT: "8080"
      PCAP_FILE: "/samples/test.pcap"
      INTERFACE: "eth0"
      PCAP_REPLAY_REALTIME: "true"
    volumes:
      - ./samples:/samples:ro
      - ./data:/app/data:ro
    cap_add: [NET_RAW, NET_ADMIN]
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
